### ISSUE TITLE
SQLiteException 비정상 종류 오류

### ISSUE THREAD

**Issue by yooonji08** [bee-p/Android_GURU#20]
## Error Log
`android.database.sqlite.SQLiteException`

### 문제 상황
> play console을 점검하던 도중 사용자의 비정상 종류 정황을 발견함
> 자세한 사항은 google play console -> 프로덕션 -> 버전 안정성 메뉴 확인 바람

### 참고 사항
> `at com.harahamzzi.android.Home.Goal.BigGoalSetupDialog$bigGoalSetup$4.onClick (BigGoalSetupDialog.kt:268)`
> https://github.com/Harahamzzi/Android_GURU/blob/b0ce03819387a6aa5fd5908c451282ea99e7a9d2/GURU_Hemjee/app/src/main/java/com/harahamzzi/android/Home/Goal/BigGoalSetupDialog.kt#L268

**Comment by Ohior** [comment]
Change this
```
var cursor = sqlitedb.rawQuery("SELECT big_goal_name FROM big_goal_db WHERE big_goal_name = '${newBigGoal}' AND color = '${newColor}';",null) 
```
To this
```
var cursor = sqlitedb.rawQuery("SELECT * FROM big_goal_db WHERE big_goal_name = ${newBigGoal} AND color = ${newColor}",null)
 ```

**Comment by yooonji08** [comment]
Hello, thank you for your answer.
I'd like to ask you a question.
Is there any reason why you answered as follows? @Ohior

**Comment by Ohior** [comment]
> Hello, thank you for your answer. I'd like to ask you a question. Is there any reason why you answered as follows? @Ohior

You are trying to query an SQL database where big_goal_name and color are true, and that is how to query the database.
This will return all the data were the expression is true

**Comment by yooonji08** [comment]
Ok. You suggested a way to search all the results and eliminate errors. Thank you for your answer.
