### ISSUE TITLE
Sliding Up Panel 오류

### ISSUE THREAD

**Issue by bee-p** [bee-p/Android_GURU#9]
## Error Log
`java.lang.IllegalStateException: Sliding up panel layout must have exactly 2 children!`

### 문제 상황
> 홈 화면 Fragment(HomeFragment)에 Sliding Up Panel을 적용하려던 상황
> 앱 실행시 해당 에러 메시지가 나오며 앱이 다운됨

### 참고 사항
> fragment_home의 container는 activity_main에 배치되어 있음
> Sliding Up Panel은 [umano의 라이브러리](https://github.com/umano/AndroidSlidingUpPanel)를 사용
> issue_1 branch에서 문제 해결 시도중

**Comment by yooonji08** [comment]
나도 새로운 프로젝트에 해당 라이브러리를 사용해보려고 하니까 오류가 나더라.. 임시방편으로 BottomSheetDialog를 사용해서 뷰를 구현하는 방법을 시도해보는 것도 좋을 것 같아! 다이얼로그 높이도 직접 설정해서 고정이 가능하고, 다이얼로그 안에서 스크롤도 구현할 수 있어!

**Comment by bee-p** [comment]
**bottom sheet dialog**로 해결
-> 특정 버튼을 누르면 bottom dialog가 나오는 방식으로 구현함
